### ISSUE TITLE
lkDpxGratingExpAnalysis-A.runPerFile

### ISSUE THREAD

**Issue by lkirkels** [duijnhouwer/DPX#10]
Hi Jacob, 

is het ook mogelijk de analyse te runnen op de hele file? Zodat je kunt zien wat het effect van verschillend contrast op de hele populatie is? En of de populatie bijvoorbeeld een bias in tuning bij voorbaat heeft? Ik geloof dat er in de toelichting wel de optie wordt genoemd, maar misschien is dit nog niet helemaal af?
- In ieder geval ga ik zelf ook even aan de slag om de responsen van de cellen te middelen

Groet, 
Laurens

**Comment by duijnhouwer** [comment]
Er is een plot van de gemiddelden van de 5 muizen, is dat wat je bedoelt?
Er is ook eeb plot met lum=all, dat zijn alle lums samen.

Ik heb de analyse trouwens van comments voorzien en gecommit

Bekijk jdDpxRdkHalfdomeAnalyse (of zo iets) eens, en probeer het een keer
op de data set. Laat me weten als er wat onduidelijk is

Jacob

**Comment by lkirkels** [comment]
Oké,  ik bedoelde meer in de analyse van 2 photon data. Daar bekijken we alles nu per cel. Vroeg me af of we dat dan weer konden middelen, zodat de respons van meerdere cellen bij elkaar wordt genomen en we iets over de populatie kunnen zeggen

Verstuurd vanaf mijn iPhone

> Op 23 jul. 2015 om 16:53 heeft duijnhouwer notifications@github.com het volgende geschreven:
> 
> Er is een plot van de gemiddelden van de 5 muizen, is dat wat je bedoelt?
> Er is ook eeb plot met lum=all, dat zijn alle lums samen.
> 
> Ik heb de analyse trouwens van comments voorzien en gecommit
> 
> Bekijk jdDpxRdkHalfdomeAnalyse (of zo iets) eens, en probeer het een keer
> op de data set. Laat me weten als er wat onduidelijk is
> 
> Jacob

**Comment by duijnhouwer** [comment]
Ah zo. Ja maar dat is dan volgende  stap. Dus dan verzamel je alle curves
per cel en daar ga je dan in n aparte analyse mee verder. Een eerste stap
is dab alle curves centreren op de voorkeursrichting waarna je kunt middelen
