### ISSUE TITLE
Analyse adaptatiebestanden

### ISSUE THREAD

**Issue by lkirkels** [duijnhouwer/DPX#3]
Hoi Jacob, 
Ik ervaar met de analyse van adaptatie bestanden nog steeds problemen. Ik weet niet of je daar al naar gekeken had

Bij anaFunc: 'DirectionTuningCurveSfTfContrast'
Error: Passed fieldname "grating_contrastFrac" is not an existing field in DPXD.

Of 

Bij anaFunc: 'DirectionTuningCurve'
Error: Passed fieldname "grating_dirDeg" is not an existing field in DPXD.

Gr. Laurens

**Comment by duijnhouwer** [comment]
easiest solution: rename all fields that start with grating_ into fields that start with test_ in your lkDpxGratingExp data

I made this tool for that: 

dpxdToolRenameFields('grating__','test__')

it will bring up a file-selection tool (suitable for multiple folders)
it will also prompt you to make backups of your data, select a folder and will copy the un-touched files into that folder.
