### ISSUE TITLE
@dpxStimDynDotQrt

### ISSUE THREAD

**Issue by agardoh** [duijnhouwer/DPX#4]
Hi Jacob,

Is it possible to help with the next situation?
 @dpxStimDynDotQrt stimulus is composed of 
Frame1: Two dots flashed simultaneously on  diagonally opposite corners of a virtual rectangle (for duration defined by flashSec)
followed by
Frame2: Two dots appear simultaneously  on the remaining two corners of the same rectangle

and this procedure is repeated in a continuous cycle for  C.durSec

It would be helpful to add another property (e.g. switchOffSec) to this stimulus:
 which allows to switch a pair of dots for a certain duration before the other two pair appear.

Concrete example of one cycle:
Two dots flashed for .15 
those two dots switched of for .1
the other two dots flashed for .15
switched of of .1

**Comment by duijnhouwer** [comment]
added pwmFrac property, pulse width modulation pwmFrac = 1 (default) is identical to not having the property
