### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by lkirkels** [duijnhouwer/DPX#8]
lkDpxToMontijn gives an error when converting grating files, not adaptation files:

> > lkDpxToMontijn
> > Reference to non-existent field 'grating_wDeg'.

Error in lkDpxToMontijn>convertLkDpxGratingExp (line 89)
    M.dblStimSizeRetinalDegrees=K.grating_wDeg(1);

Error in lkDpxToMontijn (line 19)
                structMP(i)=convertLkDpxGratingExp(dpxData); %#ok<AGROW>

Does 'grating' has to be 'test' in the function?

**Comment by duijnhouwer** [comment]
dat is precies het issue. kun je het fixen en committen?

die mountainpro is wel van github he? niet van googlecode?

had je al je gratingexp data al omgezet?

**Comment by duijnhouwer** [comment]
omgezet in de zin van grating_\* hernoemen tot test_*

**Comment by lkirkels** [comment]
Maar waarom lukt het dan wel met adaptatiefiles? Ik bedoel heb met je rename function geprobeerd om te zetten, maar het zit m dus niet in de dpx file vd stimuluscomputer maar in de conversionfunctie? En hoe krijg ik geen probleem bij de adaptatiefiles omvormen? 

Verstuurd vanaf mijn iPhone

> Op 22 jun. 2015 om 18:02 heeft duijnhouwer notifications@github.com het volgende geschreven:
> 
> omgezet in de zin van grating_\* hernoemen tot test_*
> On Jun 22, 2015 12:01 PM, "Jacob Duijnhouwer" j.duijnhouwer@gmail.com
> wrote:
> 
> > dat is precies het issue. kun je het fixen en committen?
> > 
> > die mountainpro is wel van github he? niet van googlecode?
> > 
> > had je al je gratingexp data al omgezet?

**Comment by duijnhouwer** [comment]
Dat het wel werkt met adapt maar niet met grating komt omdat lkDpxToMontijn
verschillende subfuncties heeft voor de verschillende experiment,

i.e.,
convertLkDpxGratingExp
convertLkDpxGratingAdaptExp

en dat worden er meer als er meer experimenten bijkomen (e.g.
speedContrast?)

anyway, convertLkDpxGratingExp gaat er nog vanuit dat de stimulus grating
heet, maar die heet nu test

Ik heb die nu aangepast en gecommit, probeer het eens?

Jacob

2015-06-22 12:29 GMT-04:00 lkirkels notifications@github.com:

> Maar waarom lukt het dan wel met adaptatiefiles? Ik bedoel heb met je
> rename function geprobeerd om te zetten, maar het zit m dus niet in de dpx
> file vd stimuluscomputer maar in de conversionfunctie? En hoe krijg ik geen
> probleem bij de adaptatiefiles omvormen?
> 
> Verstuurd vanaf mijn iPhone
> 
> > Op 22 jun. 2015 om 18:02 heeft duijnhouwer notifications@github.com
> > het volgende geschreven:
> > 
> > omgezet in de zin van grating_\* hernoemen tot test_*
> > On Jun 22, 2015 12:01 PM, "Jacob Duijnhouwer" j.duijnhouwer@gmail.com
> > wrote:
> > 
> > > dat is precies het issue. kun je het fixen en committen?
> > > 
> > > die mountainpro is wel van github he? niet van googlecode?
> > > 
> > > had je al je gratingexp data al omgezet?

**Comment by lkirkels** [comment]
Yes sir! Definitely works. Thanks

**Comment by duijnhouwer** [comment]
heel fijn :)
