### ISSUE TITLE
jdMovieGrating

### ISSUE THREAD

**Issue by lkirkels** [duijnhouwer/DPX#9]
Is it possible to create movies with gratings other than 0 degree?

**Comment by duijnhouwer** [comment]
nope, not as it was...
I overhauled the code, added an direciton option (aDeg, ie. angle in degrees), added a 'sqw' option (to make the greating squarewave (default) or sinewave, and renamed some existing parameters (e.g. pxHor -> pxWid and pxVer->pxHei
